// packages/ds-vue/src/components/Select/Select.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useSelect } from "./useSelect.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SelectOption = { value: string; label: string; disabled?: boolean };
export type SelectSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  options?: SelectOption[];
  value?: string | string[];
  defaultValue?: string | string[];
  onChange?: (value: string | string[]) => void;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  multiple?: boolean;
  disabled?: boolean;
  triggerLabel?: string;
  size?: SelectSize;
  filterFn?: (option: SelectOption, searchTerm: string) => boolean;
  searchable?: boolean;
  empty?: boolean;
  placeholder?: string;
  searchLabel?: string;
  position?: string;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  options: () => ([{"value":"alpha","label":"Alpha"},{"value":"beta","label":"Beta"},{"value":"gamma","label":"Gamma"}]),
  defaultValue: () => ("beta"),
  open: undefined,
  defaultOpen: true,
  multiple: undefined,
  disabled: undefined,
  triggerLabel: "Select an option",
  size: "md",
  searchable: undefined,
  empty: undefined,
  placeholder: "Select an option",
  searchLabel: "Search options",
});
// @generated:end

// @generated:start hook
const behavior = useSelect({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
  multiple: () => props.multiple,
});
function bindInteractionAnchor(element: unknown): void { behavior.anchorRef.value = element instanceof HTMLElement ? element : null; }
function bindInteractionPanel(element: unknown): void { behavior.panelRef.value = element instanceof HTMLElement ? element : null; }
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "select",
  props.size ? `select--${props.size}` : null,
  props.position ? `select--${props.position}` : null,
  behavior.open.value ? "select--open" : null,
  props.disabled ? "select--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="combobox" aria-haspopup="listbox" :aria-label="props.triggerLabel" :aria-expanded="behavior.open.value" :aria-disabled="props.disabled" :aria-controls="props.open ? `${instanceId}-content` : undefined" :data-testid="props.dataTestid" data-fsds-component="select" data-fsds-box="">
    <button :class="'select__trigger'" :ref="bindInteractionAnchor" type="button" @click="() => behavior.setOpen(!behavior.open.value)" @keydown="behavior.handleTriggerKeydown" :disabled="props.disabled" :aria-label="props.triggerLabel" :aria-expanded="behavior.open.value" :aria-controls="props.open ? `${instanceId}-content` : undefined">
      <span :class="'select__text'">
        {{ ((props.options || []).filter(option => (Array.isArray(behavior.selection.value) ? behavior.selection.value : [behavior.selection.value]).includes(option.value)).map(option => option.label).join(', ') || props.placeholder) }}
      </span>
    </button>
    <div v-if="behavior.open.value" :class="'select__content'" :ref="bindInteractionPanel" role="listbox" @keydown="behavior.handleContentKeydown" tabindex="-1" :id="`${instanceId}-content`">
      <div v-if="props.searchable" :class="'select__search'">
        <input :class="'select__searchInput'" type="text" :aria-label="props.searchLabel" :disabled="props.disabled" />
      </div>
      <div :class="'select__options'">
        <button v-for="(item, index) in (props.options ?? [])" :key="index" :class="'select__option'" role="option" type="button" @click="() => behavior.setSelection(props.multiple ? ((Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]).includes(item.value) ? (Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]).filter((v) => v !== item.value) : [...(Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]), item.value]) : item.value)" @keydown="(e) => behavior.handleOptionKeydown(e, item.value)" tabindex="-1" :aria-selected="(Array.isArray(behavior.selection.value) ? behavior.selection.value.includes(item.value) : item.value === behavior.selection.value)" :data-value="item.value" :disabled="item.disabled" :aria-disabled="item.disabled">
          <span>
            {{ item.label }}
          </span>
        </button>
      </div>
      <div v-if="props.empty" :class="'select__emptyState'"></div>
    </div>
  </div>
</template>

// packages/ds-svelte/src/components/Select/Select.svelte
<script lang="ts">
// @generated:start imports
import { useSelect } from "./useSelect.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type SelectOption = { value: string; label: string; disabled?: boolean };
type SelectSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  options?: SelectOption[];
  value?: string | string[];
  defaultValue?: string | string[];
  onChange?: (value: string | string[]) => void;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  multiple?: boolean;
  disabled?: boolean;
  triggerLabel?: string;
  size?: SelectSize;
  filterFn?: (option: SelectOption, searchTerm: string) => boolean;
  searchable?: boolean;
  empty?: boolean;
  placeholder?: string;
  searchLabel?: string;
  position?: string;
  class?: string;
}

let { options = [{"value":"alpha","label":"Alpha"},{"value":"beta","label":"Beta"},{"value":"gamma","label":"Gamma"}], value, defaultValue = "beta", onChange, open, defaultOpen = true, onOpenChange, multiple, disabled, triggerLabel = "Select an option", size = "md", filterFn, searchable, empty, placeholder = "Select an option", searchLabel = "Search options", position, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useSelect({
  value: () => value,
  defaultValue: () => defaultValue,
  onChange: () => onChange,
  open: () => open,
  defaultOpen: () => defaultOpen,
  onOpenChange: () => onOpenChange,
  multiple: () => multiple,
});
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "select",
    size ? `select--${size}` : null,
    position ? `select--${position}` : null,
    behavior.open ? "select--open" : null,
    disabled ? "select--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="combobox" aria-haspopup="listbox" aria-label={triggerLabel} aria-expanded={behavior.open} aria-disabled={disabled} aria-controls={open ? `${instanceId}-content` : undefined} data-fsds-component="select" data-fsds-box="">
  <button class={'select__trigger'} bind:this={behavior.anchorRef.el} type="button" onclick={() => behavior.setOpen(!behavior.open)} onkeydown={behavior.handleTriggerKeydown} disabled={disabled} aria-label={triggerLabel} aria-expanded={behavior.open} aria-controls={open ? `${instanceId}-content` : undefined}>
    <span class={'select__text'}>{((options || []).filter(option => (Array.isArray(behavior.selection) ? behavior.selection : [behavior.selection]).includes(option.value)).map(option => option.label).join(', ') || placeholder)}</span>
  </button>
  {#if behavior.open}
  <div class={'select__content'} bind:this={behavior.panelRef.el} role="listbox" onkeydown={behavior.handleContentKeydown} tabindex="-1" id={`${instanceId}-content`}>
    {#if searchable}
    <div class={'select__search'}>
      <input class={'select__searchInput'} type="text" aria-label={searchLabel} disabled={disabled} />
    </div>
    {/if}
    <div class={'select__options'}>
      {#each (options ?? []) as item, index (index)}
      <button class={'select__option'} role="option" type="button" onclick={() => behavior.setSelection(multiple ? ((Array.isArray(behavior.selection) ? behavior.selection : behavior.selection == null ? [] : [behavior.selection]).includes(item.value) ? (Array.isArray(behavior.selection) ? behavior.selection : behavior.selection == null ? [] : [behavior.selection]).filter((v) => v !== item.value) : [...(Array.isArray(behavior.selection) ? behavior.selection : behavior.selection == null ? [] : [behavior.selection]), item.value]) : item.value)} onkeydown={(e) => behavior.handleOptionKeydown(e, item.value)} tabindex="-1" aria-selected={(Array.isArray(behavior.selection) ? behavior.selection.includes(item.value) : item.value === behavior.selection)} data-value={item.value} disabled={item.disabled} aria-disabled={item.disabled}>
        <span>{item.label}</span>
      </button>
      {/each}
    </div>
    {#if empty}
    <div class={'select__emptyState'}></div>
    {/if}
  </div>
  {/if}
</div>
