// packages/ds-vue/src/components/Toast/Toast.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useToast } from "./useToast.js";
import { useAutoDismiss } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ToastVariant = "info" | "success" | "warning" | "error";
export type ToastPoliteness = "polite" | "assertive";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  title?: string;
  variant?: ToastVariant;
  politeness?: ToastPoliteness;
  duration?: number | null;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  variant: "info",
  politeness: "polite",
});
// @generated:end

// @generated:start hook
const behavior = useToast({
  open: () => props.open,
  onOpenChange: props.onOpenChange,
});

const autoDismiss = useAutoDismiss({
  open: () => Boolean(behavior.open.value),
  durationMs: () => props.duration === undefined ? 6000 : props.duration,
    reducedMotionSteps: 10,
  onDismiss: () => behavior.setOpen(false),
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "toast",
  props.variant ? `toast--${props.variant}` : null,
  props.politeness ? `toast--${props.politeness}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <Teleport to="body">
    <div :class="classNames" aria-label="Notifications" :aria-live="props.politeness" role="region" :data-testid="props.dataTestid" data-fsds-component="toast" data-fsds-box="" v-on="autoDismiss.pauseListeners">
      <div v-if="behavior.open.value" :class="'toast__item'" role="status" :aria-labelledby="props.title ? `${instanceId}-title` : undefined">
        <div :class="'toast__row'">
          <div v-if="props.title" :class="'toast__title'" :id="`${instanceId}-title`">
            {{ props.title }}
          </div>
          <div :class="'toast__description'">
            <slot />
          </div>
          <div v-if="$slots.action" :class="'toast__action'">
            <slot name="action" />
          </div>
          <button :class="'toast__close'" type="button" aria-label="Dismiss" @click="() => behavior.setOpen(!behavior.open.value)"></button>
        </div>
        <div :class="'toast__progress'" hidden :ref="autoDismiss.bindProgress" aria-hidden="true"></div>
      </div>
    </div>
  </Teleport>
</template>

// packages/ds-svelte/src/components/Toast/Toast.svelte
<script lang="ts">
// @generated:start imports
import { useToast } from "./useToast.svelte.js";
import { createAutoDismiss } from "../../primitives/index.js";
import { portal } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type ToastVariant = "info" | "success" | "warning" | "error";
type ToastPoliteness = "polite" | "assertive";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  title?: string;
  variant?: ToastVariant;
  politeness?: ToastPoliteness;
  duration?: number | null;
  class?: string;
  children?: import('svelte').Snippet;
  action?: import('svelte').Snippet;
}

let { open, onOpenChange, title, variant = "info", politeness = "polite", duration, class: className, children, action }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = useToast({
  open: () => open,
  onOpenChange: () => onOpenChange,
});

const autoDismiss = createAutoDismiss({
  open: () => Boolean(behavior.open),
  durationMs: () => duration === undefined ? 6000 : duration,
    reducedMotionSteps: 10,
  onDismiss: () => behavior.setOpen(false),
});
$effect(() => {
  autoDismiss.sync();
});
$effect(() => () => autoDismiss.destroy());
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "toast",
    variant ? `toast--${variant}` : null,
    politeness ? `toast--${politeness}` : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @generated:start fieldAssociation
const instanceId = $props.id();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} aria-label="Notifications" aria-live={politeness} data-fsds-component="toast" data-fsds-box="" use:portal={{ enabled: true }} onpointerenter={autoDismiss.pauseListeners.onpointerenter} onpointerleave={autoDismiss.pauseListeners.onpointerleave} onfocusin={autoDismiss.pauseListeners.onfocusin} onfocusout={autoDismiss.pauseListeners.onfocusout} role="region">
  {#if behavior.open}
  <div class={'toast__item'} role="status" aria-labelledby={title ? `${instanceId}-title` : undefined}>
    <div class={'toast__row'}>
      {#if title}
      <div class={'toast__title'} id={`${instanceId}-title`}>{title}</div>
      {/if}
      <div class={'toast__description'}>
        {@render children?.()}
      </div>
      {#if action}
      <div class={'toast__action'}>
        {@render action?.()}
      </div>
      {/if}
      <button class={'toast__close'} type="button" aria-label="Dismiss" onclick={() => behavior.setOpen(!behavior.open)}></button>
    </div>
    <div class={'toast__progress'} hidden use:autoDismiss.bindProgress aria-hidden="true"></div>
  </div>
  {/if}
</div>
