// packages/ds-angular/src/components/Select/Select.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy, ViewChild, ElementRef, signal, Injector, runInInjectionContext, untracked } from "@angular/core";
import { NgClass, NgIf, NgFor } from "@angular/common";
import { StackComponent } from "../../primitives/index.js";
import { useSelect } from "./useSelect.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SelectOption = { value: string; label: string; disabled?: boolean };
export type SelectSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
let nextInstanceId = 0;

@Component({
  selector: "fsds-select",
  standalone: true,
  imports: [NgClass, NgIf, NgFor],
  host: { "data-fsds-component": "select" },
  template: `<div [ngClass]="classes()" role="combobox" aria-haspopup="listbox" [attr.aria-label]="(triggerLabel ?? 'Select an option')" [attr.aria-expanded]="behavior.open()" [attr.aria-disabled]="disabled" [attr.aria-controls]="rootAriaControls" data-fsds-box="">
  <button [ngClass]="'select__trigger'" #interactionAnchor type="button" (click)="behavior.setOpen(!behavior.open())" (keydown)="behavior.handleTriggerKeydown($event)" [disabled]="disabled" [attr.aria-label]="(triggerLabel ?? 'Select an option')" [attr.aria-expanded]="behavior.open()" [attr.aria-controls]="triggerAriaControls">
    <span [ngClass]="'select__text'">
      {{ selectionLabel((options ?? [{'value':'alpha','label':'Alpha'},{'value':'beta','label':'Beta'},{'value':'gamma','label':'Gamma'}]), behavior.selection(), (placeholder ?? 'Select an option')) }}
    </span>
  </button>
  <ng-container *ngIf="behavior.open()">
    <div [ngClass]="'select__content'" #interactionPanel role="listbox" (keydown)="behavior.handleContentKeydown($event)" tabindex="-1" [attr.id]="instanceId + '-content'">
      <ng-container *ngIf="searchable">
        <div [ngClass]="'select__search'">
          <input [ngClass]="'select__searchInput'" type="text" [attr.aria-label]="(searchLabel ?? 'Search options')" [disabled]="disabled" />
        </div>
      </ng-container>
      <div [ngClass]="'select__options'">
        <ng-container *ngFor="let item of ((options ?? [{'value':'alpha','label':'Alpha'},{'value':'beta','label':'Beta'},{'value':'gamma','label':'Gamma'}])); let index = index">
          <button [ngClass]="'select__option'" role="option" type="button" (click)="applyToggleMembershipSelection(item.value, multiple)" (keydown)="behavior.handleOptionKeydown($event, item.value)" tabindex="-1" [attr.aria-selected]="memberOf(item.value, behavior.selection())" [attr.data-value]="item.value" [disabled]="item.disabled" [attr.aria-disabled]="item.disabled">
            <span>
              {{ item.label }}
            </span>
          </button>
        </ng-container>
      </div>
      <ng-container *ngIf="empty">
        <div [ngClass]="'select__emptyState'"></div>
      </ng-container>
    </div>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SelectComponent {
  @Input() options: SelectOption[] = [{"value":"alpha","label":"Alpha"},{"value":"beta","label":"Beta"},{"value":"gamma","label":"Gamma"}];
  private readonly inputValue = signal<string | string[] | undefined>(undefined);
  @Input() get value(): string | string[] | undefined { return this.inputValue(); }
  set value(value: string | string[] | undefined) { this.inputValue.set(value); }
  @Input() defaultValue?: string | string[] = "beta";
  @Input() onChange?: (value: string | string[]) => void;
  private readonly inputOpen = signal<boolean | undefined>(undefined);
  @Input() get open(): boolean | undefined { return this.inputOpen(); }
  set open(value: boolean | undefined) { this.inputOpen.set(value); }
  @Input() defaultOpen?: boolean = true;
  @Input() onOpenChange?: (open: boolean) => void;
  @Input() multiple?: boolean;
  @Input() disabled?: boolean;
  @Input() triggerLabel?: string = "Select an option";
  @Input() size?: SelectSize = "md";
  @Input() filterFn?: (option: SelectOption, searchTerm: string) => boolean;
  @Input() searchable?: boolean;
  @Input() empty?: boolean;
  @Input() placeholder?: string = "Select an option";
  @Input() searchLabel?: string = "Search options";
  @Input() class?: string;

  protected readonly instanceId = `fsds-select-${nextInstanceId++}`;
  @Input() position?: string;
  @ViewChild("interactionAnchor") set interactionAnchor(element: ElementRef<HTMLElement> | undefined) {
    this.behavior.anchorRef.nativeElement = element?.nativeElement ?? null;
  }
  @ViewChild("interactionPanel") set interactionPanel(element: ElementRef<HTMLElement> | undefined) {
    this.behavior.panelRef.nativeElement = element?.nativeElement ?? null;
  }

  private destroyRef = inject(DestroyRef);
  private injector = inject(Injector);
  private initializedBehavior?: ReturnType<typeof useSelect>;
  protected get behavior(): ReturnType<typeof useSelect> {
    return this.initializedBehavior ??= untracked(() => runInInjectionContext(this.injector, () => useSelect({
    value: () => this.value,
    defaultValue: this.defaultValue,
    onChange: (v) => this.onChange?.(v),
    open: () => this.open,
    defaultOpen: this.defaultOpen,
    onOpenChange: (v) => this.onOpenChange?.(v),
    multiple: () => this.multiple,
    destroyRef: this.destroyRef,
  })));
  }

  classes(): string {
    return [
      "select",
      (this.size ?? "md") ? `select--${(this.size ?? "md")}` : null,
      this.position ? `select--${this.position}` : null,
      this.behavior.open() ? "select--open" : null,
      this.disabled ? "select--disabled" : null,
      this.class,
    ].filter(Boolean).join(" ");
  }

  get rootAriaControls(): string | undefined {
    return [this.behavior.open() ? `${this.instanceId}-content` : null].filter(Boolean).join(" ") || undefined;
  }

  get triggerAriaControls(): string | undefined {
    return [this.behavior.open() ? `${this.instanceId}-content` : null].filter(Boolean).join(" ") || undefined;
  }

  // BindingExpressionV2 predicate:memberOf helper. Adapts to the runtime
  // shape of `selection`: scalar equality when not an array, set
  // membership otherwise. Used for channels typed `T | T[]`.
  protected memberOf(candidate: unknown, selection: unknown): boolean {
    return Array.isArray(selection) ? selection.includes(candidate) : candidate === selection;
  }
  protected selectionLabel(options: readonly { value: string; label: string }[] | undefined, selection: string | string[] | undefined, fallback: string): string {
    return ((options || []).filter(option => (Array.isArray(selection) ? selection : [selection]).includes(option.value)).map(option => option.label).join(', ') || fallback);
  }

  // Replace (single mode) or toggle `member`'s array membership (multi mode).
  protected applyToggleMembershipSelection(member: string, modeGate: boolean | undefined): void {
    if (!modeGate) {
      this.behavior.setSelection(member);
      return;
    }
    const currentValue = this.behavior.selection();
    const arr: string[] = Array.isArray(currentValue)
      ? [...currentValue]
      : currentValue == null ? [] : [currentValue];
    this.behavior.setSelection(arr.includes(member) ? arr.filter((v) => v !== member) : [...arr, member]);
  }
}

@Component({
  selector: "fsds-select-trigger",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="button" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SelectTriggerComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["select__trigger", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-select-content",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SelectContentComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["select__content", this.class].filter(Boolean).join(" ");
  }
}

@Component({
  selector: "fsds-select-option",
  standalone: true,
  imports: [NgClass, StackComponent],
  template: `<fsds-stack as="li" [ngClass]="classes()"><ng-content /></fsds-stack>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SelectOptionComponent {
  @Input() class?: string;
  @Input() dataTestid?: string;

  classes(): string {
    return ["select__option", this.class].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Select/Select.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useSelect } from "./useSelect.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type SelectOption = { value: string; label: string; disabled?: boolean };
export type SelectSize = "sm" | "md" | "lg";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  options?: SelectOption[];
  value?: string | string[];
  defaultValue?: string | string[];
  onChange?: (value: string | string[]) => void;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  multiple?: boolean;
  disabled?: boolean;
  triggerLabel?: string;
  size?: SelectSize;
  filterFn?: (option: SelectOption, searchTerm: string) => boolean;
  searchable?: boolean;
  empty?: boolean;
  placeholder?: string;
  searchLabel?: string;
  position?: string;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  options: () => ([{"value":"alpha","label":"Alpha"},{"value":"beta","label":"Beta"},{"value":"gamma","label":"Gamma"}]),
  defaultValue: () => ("beta"),
  open: undefined,
  defaultOpen: true,
  multiple: undefined,
  disabled: undefined,
  triggerLabel: "Select an option",
  size: "md",
  searchable: undefined,
  empty: undefined,
  placeholder: "Select an option",
  searchLabel: "Search options",
});
// @generated:end

// @generated:start hook
const behavior = useSelect({
  value: () => props.value,
  defaultValue: props.defaultValue,
  onChange: props.onChange,
  open: () => props.open,
  defaultOpen: props.defaultOpen,
  onOpenChange: props.onOpenChange,
  multiple: () => props.multiple,
});
function bindInteractionAnchor(element: unknown): void { behavior.anchorRef.value = element instanceof HTMLElement ? element : null; }
function bindInteractionPanel(element: unknown): void { behavior.panelRef.value = element instanceof HTMLElement ? element : null; }
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "select",
  props.size ? `select--${props.size}` : null,
  props.position ? `select--${props.position}` : null,
  behavior.open.value ? "select--open" : null,
  props.disabled ? "select--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="combobox" aria-haspopup="listbox" :aria-label="props.triggerLabel" :aria-expanded="behavior.open.value" :aria-disabled="props.disabled" :aria-controls="props.open ? `${instanceId}-content` : undefined" :data-testid="props.dataTestid" data-fsds-component="select" data-fsds-box="">
    <button :class="'select__trigger'" :ref="bindInteractionAnchor" type="button" @click="() => behavior.setOpen(!behavior.open.value)" @keydown="behavior.handleTriggerKeydown" :disabled="props.disabled" :aria-label="props.triggerLabel" :aria-expanded="behavior.open.value" :aria-controls="props.open ? `${instanceId}-content` : undefined">
      <span :class="'select__text'">
        {{ ((props.options || []).filter(option => (Array.isArray(behavior.selection.value) ? behavior.selection.value : [behavior.selection.value]).includes(option.value)).map(option => option.label).join(', ') || props.placeholder) }}
      </span>
    </button>
    <div v-if="behavior.open.value" :class="'select__content'" :ref="bindInteractionPanel" role="listbox" @keydown="behavior.handleContentKeydown" tabindex="-1" :id="`${instanceId}-content`">
      <div v-if="props.searchable" :class="'select__search'">
        <input :class="'select__searchInput'" type="text" :aria-label="props.searchLabel" :disabled="props.disabled" />
      </div>
      <div :class="'select__options'">
        <button v-for="(item, index) in (props.options ?? [])" :key="index" :class="'select__option'" role="option" type="button" @click="() => behavior.setSelection(props.multiple ? ((Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]).includes(item.value) ? (Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]).filter((v) => v !== item.value) : [...(Array.isArray(behavior.selection.value) ? behavior.selection.value : behavior.selection.value == null ? [] : [behavior.selection.value]), item.value]) : item.value)" @keydown="(e) => behavior.handleOptionKeydown(e, item.value)" tabindex="-1" :aria-selected="(Array.isArray(behavior.selection.value) ? behavior.selection.value.includes(item.value) : item.value === behavior.selection.value)" :data-value="item.value" :disabled="item.disabled" :aria-disabled="item.disabled">
          <span>
            {{ item.label }}
          </span>
        </button>
      </div>
      <div v-if="props.empty" :class="'select__emptyState'"></div>
    </div>
  </div>
</template>
