// packages/ds-svelte/src/components/PageNavigator/PageNavigator.svelte
<script lang="ts">
// @generated:start imports
import { usePageNavigator } from "./usePageNavigator.svelte.js";
import Button from "../Button/Button.svelte";
import Icon from "../Icon/Icon.svelte";
import Input from "../Input/Input.svelte";
import Pagination from "../Pagination/Pagination.svelte";
import { createReactivePagedSet } from "../../primitives/paging.svelte.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
type PageNavigatorPresentation = "indicators" | "pages";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  pages?: string[];
  index?: number;
  defaultIndex?: number;
  onIndexChange?: (index: number) => void;
  presentation?: PageNavigatorPresentation;
  label?: string;
  disabled?: boolean;
  pageCount?: number;
  pageLabel?: string;
  previousLabel?: string;
  nextLabel?: string;
  ofLabel?: string;
  commitLabel?: string;
  showChoices?: boolean;
  class?: string;
}

let { pages = [], index, defaultIndex = 0, onIndexChange, presentation = "indicators", label = "Page navigation", disabled = false, pageCount, pageLabel = "Current page", previousLabel = "Previous page", nextLabel = "Next page", ofLabel = "of", commitLabel = "Go", showChoices = false, class: className }: Props = $props();
// @generated:end

// @generated:start hook
const behavior = usePageNavigator({
  index: () => index,
  defaultIndex: () => defaultIndex,
  onIndexChange: () => onIndexChange,
});
const pagedSet = createReactivePagedSet();
$effect(() => { pagedSet.sync({ index: behavior.page, items: pages,
  count: pageCount, disabled: disabled, onIndexChange: behavior.setPage }); });
$effect(() => () => pagedSet.destroy());
// @generated:end

// @generated:start classes
const classes = $derived(
  [
    "page-navigator",
    disabled ? "page-navigator--disabled" : null,
    className,
  ].filter(Boolean).join(" ")
);
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<div class={classes} role="group" aria-label={label} data-fsds-component="page-navigator" data-fsds-box="">
  <Button class={'page-navigator__previous'} type="button" onClick={pagedSet.previous} disabled={pagedSet.state.previousDisabled} ariaLabel={previousLabel}>
    <Icon class={'page-navigator__previousIcon'} name="arrow-left" size="sm" />
  </Button>
  <div class={'page-navigator__field'} onkeydown={pagedSet.commitOnEnter} onfocusout={pagedSet.commit}>
    <Input class={'page-navigator__input'} type="number" onChange={pagedSet.edit} value={pagedSet.state.draft} disabled={pagedSet.state.disabled} ariaLabel={pageLabel} />
  </div>
  <span class={'page-navigator__context'}>{ofLabel}</span>
  <span class={'page-navigator__total'}>{pagedSet.state.count}</span>
  <Button class={'page-navigator__commit'} type="button" onClick={pagedSet.commit} disabled={pagedSet.state.disabled} ariaLabel={commitLabel}>
    <span>{commitLabel}</span>
  </Button>
  <Button class={'page-navigator__next'} type="button" onClick={pagedSet.next} disabled={pagedSet.state.nextDisabled} ariaLabel={nextLabel}>
    <Icon class={'page-navigator__nextIcon'} name="arrow-right" size="sm" />
  </Button>
  {#if showChoices}
  <Pagination class={'page-navigator__choices'} onIndexChange={pagedSet.request} pages={pages} index={behavior.page} presentation={presentation} label={label} disabled={pagedSet.state.disabled} />
  {/if}
</div>

// packages/ds-angular/src/components/PageNavigator/PageNavigator.component.ts
// @generated:start imports
import { Component, Input, computed, DestroyRef, inject, ChangeDetectionStrategy, effect, signal, Injector, runInInjectionContext, untracked } from "@angular/core";
import { NgClass, NgIf } from "@angular/common";
import { createReactivePagedSet } from "../../primitives/paging-signal.js";
import { ButtonComponent } from "../Button/Button.component.js";
import { IconComponent } from "../Icon/Icon.component.js";
import { InputComponent } from "../Input/Input.component.js";
import { PaginationComponent } from "../Pagination/Pagination.component.js";
import { usePageNavigator } from "./usePageNavigator.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PageNavigatorPresentation = "indicators" | "pages";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start component
@Component({
  selector: "fsds-page-navigator",
  standalone: true,
  imports: [NgClass, NgIf, ButtonComponent, IconComponent, InputComponent, PaginationComponent],
  host: { "data-fsds-component": "page-navigator" },
  template: `<div [ngClass]="classes()" role="group" [attr.aria-label]="(label ?? 'Page navigation')" data-fsds-box="">
  <fsds-button [ngClass]="'page-navigator__previous'" type="button" [onClick]="pagedSet.previous" [disabled]="pagedSet.state.previousDisabled" [ariaLabel]="(previousLabel ?? 'Previous page')">
    <fsds-icon [ngClass]="'page-navigator__previousIcon'" name="arrow-left" size="sm"></fsds-icon>
  </fsds-button>
  <div [ngClass]="'page-navigator__field'" (keydown)="pagedSet.commitOnEnter($event)" (focusout)="pagedSet.commit()">
    <fsds-input [ngClass]="'page-navigator__input'" type="number" [onChange]="pagedSet.edit" [value]="pagedSet.state.draft" [disabled]="pagedSet.state.disabled" [ariaLabel]="(pageLabel ?? 'Current page')"></fsds-input>
  </div>
  <span [ngClass]="'page-navigator__context'">
    {{ (ofLabel ?? 'of') }}
  </span>
  <span [ngClass]="'page-navigator__total'">
    {{ pagedSet.state.count }}
  </span>
  <fsds-button [ngClass]="'page-navigator__commit'" type="button" [onClick]="pagedSet.commit" [disabled]="pagedSet.state.disabled" [ariaLabel]="(commitLabel ?? 'Go')">
    <span>
      {{ (commitLabel ?? 'Go') }}
    </span>
  </fsds-button>
  <fsds-button [ngClass]="'page-navigator__next'" type="button" [onClick]="pagedSet.next" [disabled]="pagedSet.state.nextDisabled" [ariaLabel]="(nextLabel ?? 'Next page')">
    <fsds-icon [ngClass]="'page-navigator__nextIcon'" name="arrow-right" size="sm"></fsds-icon>
  </fsds-button>
  <ng-container *ngIf="showChoices">
    <fsds-pagination [ngClass]="'page-navigator__choices'" [onIndexChange]="pagedSet.request" [pages]="(pages ?? [])" [index]="behavior.page()" [presentation]="(presentation ?? 'indicators')" [label]="(label ?? 'Page navigation')" [disabled]="pagedSet.state.disabled"></fsds-pagination>
  </ng-container>
</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PageNavigatorComponent {
  private readonly inputPages = signal<string[] | undefined>(undefined);
  @Input() get pages(): string[] | undefined { return this.inputPages(); }
  set pages(value: string[] | undefined) { this.inputPages.set(value); }
  private readonly inputIndex = signal<number | undefined>(undefined);
  @Input() get index(): number | undefined { return this.inputIndex(); }
  set index(value: number | undefined) { this.inputIndex.set(value); }
  @Input() defaultIndex?: number = 0;
  @Input() onIndexChange?: (index: number) => void;
  @Input() presentation?: PageNavigatorPresentation = "indicators";
  @Input() label?: string = "Page navigation";
  private readonly inputDisabled = signal<boolean | undefined>(undefined);
  @Input() get disabled(): boolean | undefined { return this.inputDisabled(); }
  set disabled(value: boolean | undefined) { this.inputDisabled.set(value); }
  private readonly inputPageCount = signal<number | undefined>(undefined);
  @Input() get pageCount(): number | undefined { return this.inputPageCount(); }
  set pageCount(value: number | undefined) { this.inputPageCount.set(value); }
  @Input() pageLabel?: string = "Current page";
  @Input() previousLabel?: string = "Previous page";
  @Input() nextLabel?: string = "Next page";
  @Input() ofLabel?: string = "of";
  @Input() commitLabel?: string = "Go";
  @Input() showChoices?: boolean = false;
  @Input() class?: string;

  private destroyRef = inject(DestroyRef);
  private injector = inject(Injector);
  private initializedBehavior?: ReturnType<typeof usePageNavigator>;
  protected get behavior(): ReturnType<typeof usePageNavigator> {
    return this.initializedBehavior ??= untracked(() => runInInjectionContext(this.injector, () => usePageNavigator({
    index: () => this.index,
    defaultIndex: this.defaultIndex,
    onIndexChange: (v) => this.onIndexChange?.(v),
    destroyRef: this.destroyRef,
  })));
  }
  protected pagedSet = createReactivePagedSet();
  private pagedCleanup = this.destroyRef.onDestroy(() => this.pagedSet.destroy());
  private pagedEffect = effect(() => this.pagedSet.sync({ index: this.behavior.page(), items: this.pages ?? [],
    count: this.pageCount, disabled: this.disabled, onIndexChange: (value) => this.behavior.setPage(value) }));

  classes(): string {
    return [
      "page-navigator",
      (this.disabled ?? false) ? "page-navigator--disabled" : null,
      this.class,
    ].filter(Boolean).join(" ");
  }
}
// @generated:end

// @custom:start trailing

// @custom:end
