// packages/ds-react/src/components/Pagination/Pagination.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode } from "react";
import { Stack } from "../../primitives";
import { usePagination } from "./usePagination";
import { usePagedSet } from "../../primitives/hooks/usePaging.js";
import "./Pagination.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PaginationPresentation = "indicators" | "pages";

export type PaginationProgress = "none" | "elapsed";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface PaginationProps extends Omit<HTMLAttributes<HTMLDivElement>, "children" | "className" | "data-testid" | "defaultIndex" | "disabled" | "index" | "label" | "onIndexChange" | "pages" | "presentation" | "progress"> {
  pages?: string[];
  index?: number;
  defaultIndex?: number;
  onIndexChange?: (index: number) => void;
  presentation?: PaginationPresentation;
  label?: string;
  disabled?: boolean;
  progress?: PaginationProgress;
  className?: string;
  "data-testid"?: string;
}
// @generated:end

// @generated:start subcomponents

// @generated:end

// @generated:start component
export function Pagination({
  index: controlledIndex,
  defaultIndex = 0,
  onIndexChange,
  presentation = "indicators",
  progress = "none",
  disabled,
  className,
  "data-testid": testId,
  pages = [],
  label = "Choose page",
  ...rest
}: PaginationProps) {
  const { page, setPage } = usePagination({
    index: controlledIndex,
    defaultIndex,
    onIndexChange,
  });

  const pagedSet = usePagedSet({ index: page, items: pages,
    count: undefined, disabled: disabled, onIndexChange: setPage });
  const classNames = [
    "pagination",
    presentation && `pagination--${presentation}`,
    progress && `pagination--${progress}`,
    disabled && "pagination--disabled",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
  <Stack layout="native" className={`${classNames}`} role="group" aria-label={label} data-testid={testId} data-fsds-component="pagination" data-fsds-box="" {...rest}>
    {(pages ?? []).map((item, index) => (
      <button className="pagination__item" type="button" onClick={() => pagedSet.request(index)} aria-label={item} aria-current={(index === page)} disabled={disabled} data-current={(index === page)} key={index}>
        <span className="pagination__marker" aria-hidden="true">
          <span className="pagination__fill" aria-hidden="true" />
        </span>
        <span className="pagination__label" aria-hidden="true">
          {item}
        </span>
      </button>
    ))}
  </Stack>
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Pagination/Pagination.vue
<script setup lang="ts">
// @generated:start imports
import { computed } from "vue";
import { usePagination } from "./usePagination.js";
import { usePagedSet } from "../../primitives/hooks/usePaging.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type PaginationPresentation = "indicators" | "pages";
export type PaginationProgress = "none" | "elapsed";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  pages?: string[];
  index?: number;
  defaultIndex?: number;
  onIndexChange?: (index: number) => void;
  presentation?: PaginationPresentation;
  label?: string;
  disabled?: boolean;
  progress?: PaginationProgress;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  pages: () => ([]),
  defaultIndex: 0,
  presentation: "indicators",
  label: "Choose page",
  disabled: false,
  progress: "none",
});
// @generated:end

// @generated:start hook
const behavior = usePagination({
  index: () => props.index,
  defaultIndex: props.defaultIndex,
  onIndexChange: props.onIndexChange,
});
const pagedSet = usePagedSet(() => ({ index: behavior.page.value, items: props.pages,
  count: undefined, disabled: props.disabled, onIndexChange: behavior.setPage }));
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "pagination",
  props.presentation ? `pagination--${props.presentation}` : null,
  props.progress ? `pagination--${props.progress}` : null,
  props.disabled ? "pagination--disabled" : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <div :class="classNames" role="group" :aria-label="props.label" :data-testid="props.dataTestid" data-fsds-component="pagination" data-fsds-box="">
    <button v-for="(item, index) in (props.pages ?? [])" :key="index" :class="'pagination__item'" type="button" @click="() => pagedSet.request(index)" :aria-label="item" :aria-current="(index === behavior.page.value)" :disabled="props.disabled" :data-current="(index === behavior.page.value)">
      <span :class="'pagination__marker'" aria-hidden="true">
        <span :class="'pagination__fill'" aria-hidden="true"></span>
      </span>
      <span :class="'pagination__label'" aria-hidden="true">
        {{ item }}
      </span>
    </button>
  </div>
</template>
