// packages/ds-react/src/components/Toast/Toast.tsx
// @generated:start imports
import { type HTMLAttributes, type ReactNode, useId } from "react";
import { Stack } from "../../primitives";
import { useToast } from "./useToast";
import { useAutoDismiss } from "../../primitives/hooks";
import "./Toast.css";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ToastVariant = "info" | "success" | "warning" | "error";

export type ToastPoliteness = "polite" | "assertive";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
export interface ToastProps extends Omit<HTMLAttributes<HTMLDivElement>, "children" | "className" | "data-testid" | "duration" | "onOpenChange" | "open" | "politeness" | "title" | "variant"> {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  title?: string;
  variant?: ToastVariant;
  politeness?: ToastPoliteness;
  duration?: number | null;
  className?: string;
  "data-testid"?: string;
  children?: ReactNode;
  slots?: {
    action?: ReactNode;
  };
}
// @generated:end

// @generated:start subcomponents
export interface ToastItemProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function ToastItem({
  children,
  className,
  "data-testid": testId,
}: ToastItemProps) {
  const classNames = ["toast__item", className].filter(Boolean).join(" ");
  return (
    <Stack as="li" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface ToastTitleProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function ToastTitle({
  children,
  className,
  "data-testid": testId,
}: ToastTitleProps) {
  const classNames = ["toast__title", className].filter(Boolean).join(" ");
  return (
    <Stack as="h3" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}

export interface ToastDescriptionProps {
  children?: ReactNode;
  className?: string;
  "data-testid"?: string;
}

export function ToastDescription({
  children,
  className,
  "data-testid": testId,
}: ToastDescriptionProps) {
  const classNames = ["toast__description", className].filter(Boolean).join(" ");
  return (
    <Stack as="p" className={classNames} data-testid={testId}>
      {children}
    </Stack>
  );
}
// @generated:end

// @generated:start component
export function Toast({
  open: controlledOpen,
  onOpenChange,
  variant = "info",
  politeness = "polite",
  className,
  "data-testid": testId,
  children,
  title,
  duration,
  slots,
  ...rest
}: ToastProps) {
  const { open, setOpen, renderInPortal } = useToast({
    open: controlledOpen,
    onOpenChange,
  });

  const autoDismiss = useAutoDismiss({
    open: Boolean(open),
    durationMs: duration === undefined ? 6000 : duration,
    reducedMotionSteps: 10,
    onDismiss: () => setOpen(false),
  });
  const autoDismissPauseProps = autoDismiss.getPauseProps();

  const classNames = [
    "toast",
    variant && `toast--${variant}`,
    politeness && `toast--${politeness}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const instanceId = useId();

  return (
    renderInPortal(
    <Stack layout="native" className={`${classNames}`} aria-label="Notifications" aria-live={politeness} role="region" data-testid={testId} data-fsds-component="toast" data-fsds-box="" {...autoDismissPauseProps} {...rest}>
      {open ? (
        <div className="toast__item" role="status" aria-labelledby={title ? `${instanceId}-title` : undefined}>
          <div className="toast__row">
            {title ? (
              <div className="toast__title" id={`${instanceId}-title`}>
                {title}
              </div>
            ) : null}
            <div className="toast__description">
              {children}
            </div>
            {slots?.action ? (
              <div className="toast__action">
                {slots?.action}
              </div>
            ) : null}
            <button className="toast__close" type="button" aria-label="Dismiss" onClick={() => setOpen(!open)} />
          </div>
          <div className="toast__progress" hidden ref={autoDismiss.bindProgress} aria-hidden="true" />
        </div>
      ) : null}
    </Stack>
    )
  );
}
// @generated:end

// @custom:start trailing

// @custom:end

// packages/ds-vue/src/components/Toast/Toast.vue
<script setup lang="ts">
// @generated:start imports
import { computed, useId } from "vue";
import { useToast } from "./useToast.js";
import { useAutoDismiss } from "../../primitives/index.js";
// @generated:end

// @custom:start imports

// @custom:end

// @generated:start types
export type ToastVariant = "info" | "success" | "warning" | "error";
export type ToastPoliteness = "polite" | "assertive";
// @generated:end

// @custom:start types

// @custom:end

// @generated:start props
interface Props {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  title?: string;
  variant?: ToastVariant;
  politeness?: ToastPoliteness;
  duration?: number | null;
  class?: string;
  dataTestid?: string;
}
// @generated:end

// @generated:start defineProps
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  variant: "info",
  politeness: "polite",
});
// @generated:end

// @generated:start hook
const behavior = useToast({
  open: () => props.open,
  onOpenChange: props.onOpenChange,
});

const autoDismiss = useAutoDismiss({
  open: () => Boolean(behavior.open.value),
  durationMs: () => props.duration === undefined ? 6000 : props.duration,
    reducedMotionSteps: 10,
  onDismiss: () => behavior.setOpen(false),
});
// @generated:end

// @generated:start classes
const classNames = computed(() => [
  "toast",
  props.variant ? `toast--${props.variant}` : null,
  props.politeness ? `toast--${props.politeness}` : null,
  props.class,
].filter(Boolean).join(" "));
// @generated:end

// @generated:start fieldAssociation
const instanceId = useId();
// @generated:end

// @custom:start trailing

// @custom:end
</script>

<template>
  <Teleport to="body">
    <div :class="classNames" aria-label="Notifications" :aria-live="props.politeness" role="region" :data-testid="props.dataTestid" data-fsds-component="toast" data-fsds-box="" v-on="autoDismiss.pauseListeners">
      <div v-if="behavior.open.value" :class="'toast__item'" role="status" :aria-labelledby="props.title ? `${instanceId}-title` : undefined">
        <div :class="'toast__row'">
          <div v-if="props.title" :class="'toast__title'" :id="`${instanceId}-title`">
            {{ props.title }}
          </div>
          <div :class="'toast__description'">
            <slot />
          </div>
          <div v-if="$slots.action" :class="'toast__action'">
            <slot name="action" />
          </div>
          <button :class="'toast__close'" type="button" aria-label="Dismiss" @click="() => behavior.setOpen(!behavior.open.value)"></button>
        </div>
        <div :class="'toast__progress'" hidden :ref="autoDismiss.bindProgress" aria-hidden="true"></div>
      </div>
    </div>
  </Teleport>
</template>
